services:
  - type: web
    name: shotdev
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: 'true'
