services:
  - type: web
    name: shots
    env: node
    region: oregon
    plan: starter
    buildCommand: |
      pnpm install
      pnpm build
    startCommand: node .output/server/index.mjs
    envVars:
      - key: NODE_ENV
        value: production
